### ISSUE TITLE
Getting access to the QP costs

### ISSUE THREAD

**Issue by lothas** [robotology/OpenSoT#109]
I need to have access to the QP cost (at least at the top level, though access to the cost and solutions at all levels would be helpful) for a learning algorithm that I'm developing.

I implemented my own derived class of OpenSoT::solvers::QPOases_sot as a work-around and added the following methods:

```
    /**
     * @brief Function that computes and returns the cost of each qp on the stack
     * @return Eigen::VectorXd of the costs
     */
    Eigen::VectorXd getQPCost() {
        Eigen::VectorXd costs(_qp_stack_of_tasks.size());
        for (unsigned int i = 0; i < _qp_stack_of_tasks.size(); ++i) {
            // For each QP problem in the stack
            Eigen::VectorXd sol = _qp_stack_of_tasks[i].getSolution();
            Eigen::MatrixXd H = _qp_stack_of_tasks[i].getH();
            Eigen::VectorXd g = _qp_stack_of_tasks[i].getg();

            Eigen::VectorXd cost = H*sol - g;
            costs(i) = cost.norm();
        }
        return costs;
    }

    /**
     * @brief Function that returns the solution of the top qp on the stack
     * @return const Eigen::VectorXd with the solution
     */
    const Eigen::VectorXd &getSolution() {
        return _qp_stack_of_tasks[0].getSolution();
    } 
```

**Comment by EnricoMingo** [comment]
@lothas , I am working on this in the ```issue109``` branch. Already implemented I just need couple of small tests. Wait for upgrade because I am updating the OpenSoT-superbuild. you will also have to change couple lines of code due to the last development.

**Comment by EnricoMingo** [comment]
Tested and merged in ```devel```. Pay attention that the implemented method, ```getObjective()``` return the value of the objective function at the optimum (which could be also negative in general) and not its norm2.
