### ISSUE TITLE
Solver EPS (normalization term) handling

### ISSUE THREAD

**Issue by EnricoMingo** [robotology/OpenSoT#115]
Now that we have two qp-based backends there is the problem of the handling of the eps paramter to have the same value used despite the qp solver.
In qpOASES the user input parameter was always multiplied by the internal one (which is aorund 10e-13) while is OSQP the value is direclty used. 
I propose to go as in OSPQ so the user value overwrite directly the internal one.

**Comment by EnricoMingo** [comment]
There are two possible solutions: 

1.  OSQP eps is handled as qpOASES one where there is a default value, which is low (something to the power of -13) and new values multiply this value
2. qpOASES eps is handled as OSQP were default is 0 and new values are directly applied

Which is better? Probably from the user point of view is better to always have a little of normalization?

**Comment by alaurenzi** [comment]
I like the first, plus a `getDefaultRegularization` method returning the base value

**Comment by EnricoMingo** [comment]
Ok, in ```OSQPBackEnd.cpp```, in method ```updateTask(...)```, the ```_eps_regularisation``` is multiplied by ```BASE_REGULARISATION``` which value is ```1e-12``` as the base one in qpOASES. Done in ```eps_regularisation``` branch and merged in ```devel```.
