### ISSUE TITLE
Migrate OpenSoT to Eigen and KDL

### ISSUE THREAD

**Issue by EnricoMingo** [robotology/OpenSoT#25]
Sooner or later...

**Comment by facontidavide** [comment]
That would be awesome ;)

Pragmatically speaking it would allow a much large community to join.

**Comment by liesrock** [comment]
I can help on this ;)

**Comment by traversaro** [comment]
I suggest a first step: 
* [ ] help me get a working OpenSoT installation so I can check the UnitTests against the new iDynTree with optional YARP dependency.

**Comment by EnricoMingo** [comment]
To facontidavide: yes indeed!
To liesrock: thanks! We count on you!
To traversaro: ok!

**Comment by EnricoMingo** [comment]
Ok, I am doing this dirty work in branch v2.0
- solver is full Eigen now
- tasks and constraints are half-eigen and yarp (model side)

**Comment by EnricoMingo** [comment]
The migration is almost finished (just couple of tasks and tests are missing). Furthermore the framework has grown and tested in RT. I'll close.
