### ISSUE TITLE
[examples] bring over useful examples from old project sot_VelKinCon

### ISSUE THREAD

**Issue by arocchi** [robotology/OpenSoT#36]
especially intertesting examples:
1) using KDL to obtain kinematic information for the robot in Python
2) mixing TF/KDL/OpenSoT in Python

**Comment by EnricoMingo** [comment]
Can we close this?

**Comment by arocchi** [comment]
Tasks:
- [ ] bring over the SVG follower (python) demo to OpenSoT (updated to use new python data structures)
- [ ] check tests, bring them over to OpenSoT with more meaningful names (i.e., some tests use old pydrc python bindings with KDL and TF such as testCoM), provide alternative implementations

**Comment by EnricoMingo** [comment]
I think we can close at this point.
