### ISSUE TITLE
Dynamics velocity constraint (torque limits) improvement

### ISSUE THREAD

**Issue by arocchi** [robotology/OpenSoT#42]
As of now, in order to always have a feasible torque limits constraint, the bounds are computed so that the constraint is never repulsive, i.e.:

```
    for(unsigned int i =0; i < _b.size(); ++i)
    {
        _bLowerBound[i] = std::min(_bLowerBound[i],0.0);
        _bUpperBound[i] = std::max(_bUpperBound[i],0.0);
    }
```

instead of using `0.0` we should have the velocity limits, so that the limits are still feasible but also repulsive

**Comment by EnricoMingo** [comment]
I'll close
