### ISSUE TITLE
Moving to robotology?

### ISSUE THREAD

**Issue by pattacini** [robotology/OpenSoT#46]
Hi @arocchi @liesrock 

Is there any particular reason why this repository hasn't been moved to our official organization [**`robotology`**](https://github.com/robotology) yet?

**OpenSoT** appears to be much more than mature by now and **`robotology-playground`** is intended as mere collector for early stage developments.

Also, consider that, once moved (if you'll decide to do so), GitHub will automatically redirect users visiting stale web links towards the new location.

**Comment by pattacini** [comment]
cc @robotology-playground/walkman-sprinters

**Comment by liesrock** [comment]
Hi Ugo,
sorry for the delay: from my knowledge this is something that was already done when I came, but I think that now we are ready to move to the [**`robotology`**](https://github.com/robotology) the following repo:

- robotology-superbuild 
- GYM
- OpenSoT
- idynutils

**Comment by pattacini** [comment]
Hi Luca,

- [x] **OpenSoT** has been just moved. I've created the corresponding team in **robotology** and asked people to join; @corradopav @fcdean @krprzemo still pending.

- [ ] **robotology-superbuild** seems still quite anonymous from a user standpoint. I think a bit of documentation is still required, at least in the _README.md_ file.

- [ ] **idynutils** is a good candidate to be in robotology, but still I think documentation can be improved.

- [ ] Conversely, **GYM** appears to be in a very good status documentation-wise, but given that it deals with a tutorial on **YARP** modules I'd rather wait for @drdanz @lornat75 to chime in to avoid any type of clash.

**Comment by pattacini** [comment]
Better to talk about other repos in their respective issue tracking systems.
Closing then.
