### ISSUE TITLE
[v2.0] Strange behaviour for 2 tests

### ISSUE THREAD

**Issue by EnricoMingo** [robotology/OpenSoT#56]
There are two unit tests, CoMForce and FrictionConeConstraint ,that has a very strange behaviour: basically when compiling in Debug mode both are passing using gtets while mostly of the time they fails in ctest. If I compile in release,, CoMForce pass in ctest but fails in gtest, FrictionConeConstraint pass in gtest but fail in ctest...

**Comment by EnricoMingo** [comment]
Today I run many times the tests using ctest and they always passed...

**Comment by traversaro** [comment]
Have you tried running them under Valgrind? This stinks of non initialized memory.

**Comment by EnricoMingo** [comment]
Not yet, thanks for the suggestion!

**Comment by EnricoMingo** [comment]
Solved. It was due to the fact that qpOASES does not like unbounded problems. Adding bounds it solves.
