### ISSUE TITLE
OpenSoT [lite] dependent on cartesian_utils

### ISSUE THREAD

**Issue by krprzemo** [robotology/OpenSoT#70]
Hi guys, 
I am a bit out of date with the whole superbuild set up. I am trying to compile Juan_FBcontrollers which depends on OpenSoT. The only project I found in the ccmake's list was OpenSoT-lite. After enabling it and trying to compile I get error that cartesian_utilsConfig.cmake is not present. I tried to look for cartesian_utils in cmake projects list. but couldn't find one. Grep on the superbuild shows that there is cartesian_utils in idynutils. I have it enabled and compiled, but it doesn't solve the problem and I guess that's not the way. 
Can you guys let me know:
- which OpenSoT branch/tag is now used by superbuild (is the 'lite' tag the right thing to use)?
- what are the current dependent projects which need to be enabled in the cmake configuration of superbuild to compile OpenSoT?
Thanks in advance !!!

**Comment by EnricoMingo** [comment]
Hi @krprzemo ! OpenSoT-lite and OpenSoT are actually the exact same thing. Despite the two you are using, you should checkout to the v2.0 version that is based on Eigen and the ModelInterface (we are using RBDL) inside.
