### ISSUE TITLE
OpenSoT is crashing on assert in DEBUG Mode

### ISSUE THREAD

**Issue by liesrock** [robotology/OpenSoT#71]
I am trying to define a Cartesian task and if I compile OpenSoT in RELEASE mode I do not have any problems (I am able to control the robot), but if it is compiled in DEBUG mode I receive the following error:

```
gzserver: /home/visionpc2/advr-superbuild/external/OpenSoT-lite/src/tasks/velocity/Cartesian.cpp:49: OpenSoT::tasks::velocity::Cartesian::Cartesian(std::string, const VectorXd&, XBot::ModelInterface&, std::string, std::string): Assertion `this->_distal_link_index >= 0' failed.
```

**Comment by liesrock** [comment]
The OpenSoT plugin I am using inside GazeboXBotPlugin is here: https://github.com/ADVRHumanoids/MiscellaneousPlugins/blob/master/src/OpenSotIk.cpp

**Comment by EnricoMingo** [comment]
Solved. The problem is related to compatibility with rbdl. Basically to some links are assigned large negative random numbers (while using idyntree we were just using positive numbers). I will not do anymore  checks in OpenSoT code but should be nice that the ModelInterface takes care of it.

**Comment by liesrock** [comment]
Ok! In which commit did you solve it?
Can you open an issue on XBotInterface for the checks on ModelInterface?
