### ISSUE TITLE
Add the ability to activate / deactivate a task.

### ISSUE THREAD

**Issue by alaurenzi** [robotology/OpenSoT#72]
Right now if I want to deactivate a task online, the only option is to set the corresponding weight to zero, and the re-set it to the original value when the task has to be reactivated. This leads to a very verbose code like the following

```
if(_contact_state[i]){
            _contact_tasks[i]->setWeight(Eigen::MatrixXd::Identity(_contact_matrix[i].rows(), _contact_matrix[i].rows()));
            _feet_cartesian_tasks[i]->setWeight(Eigen::MatrixXd::Zero(6, 6));
        }
        else{
            _contact_tasks[i]->setWeight(Eigen::MatrixXd::Zero(_contact_matrix[i].rows(), _contact_matrix[i].rows()));
            _feet_cartesian_tasks[i]->setWeight(Eigen::MatrixXd::Identity(6, 6));
         }
}
```

It would be nice if the Task interface provided a means to achieve the same result with less code, for example

```
task->activate();
task->deactivate();
```

**Comment by EnricoMingo** [comment]
Indeed this can be done as for the atcive_joint_mask: in the Task.h we can define a ```setActive(bool)``` that in the ```update()``` set to 0 the weights.

**Comment by EnricoMingo** [comment]
There is a branch called deactivate_stack which provide this feature. I added also a test that looks like is working. Maybe another test in which also the first stack is deactivate should be added.

**Comment by EnricoMingo** [comment]
Tested and merged to devel.
