### ISSUE TITLE
autostack class with one task

### ISSUE THREAD

**Issue by InriaBrice** [robotology/OpenSoT#84]
Hi !

We would like to have just a posture task with some joints and velocities limit. To do so we tryed : 

auto_stack_ = (postural_) << joint_lims_ << vel_lims_;

But this give an error compilation

Best regards,
Brice

**Comment by EnricoMingo** [comment]
Solved in last ```devel``` commit (```8dd598a94cf923bcc52995e0a6862fe9b20531b0```).
You can now create a single stack autostack in the following way:

`AutoStack::Ptr autostack(new AutoStack(DHS->postural)); `
 `autostack = autostack<<DHS->jointLimits<<DHS->velocityLimits;`

I'll close.
