### ISSUE TITLE
Major bug in AutoStack::operator+(Aggregated, Aggregated)

### ISSUE THREAD

**Issue by alaurenzi** [robotology/OpenSoT#85]
A W1xW1 block is assigned to a W2xW2 matrix. Eigen does not complain in release mode if assertions are not manually enabled (which I suggest to do), and all kind of weird memory corruptions happen. Fixing it with e6ad6d3e460ace3860a3fb1b3bac3d598d on contact_task branch (you may consider to cherry-pick it)

**Comment by EnricoMingo** [comment]
Cherry-Picked into ```devel```. Thanks, I'll close.
