### ISSUE TITLE
[devel] Test rt with WALK-MAN demo stack

### ISSUE THREAD

**Issue by EnricoMingo** [robotology/OpenSoT#92]
Last massive changes may had introduced rt issues. With @alaurenzi  we have tested everything on Xenomai and it works with 2 stacks. A further test should be done with the stack of WALK-MAN which is  levels.
The reference commit is ```51f15d4b78a92b4b104aa4c10ffc50e30c50bf7c```

**Comment by EnricoMingo** [comment]
Done and working.

**Comment by liesrock** [comment]
Sleep well.
